global:
  scrape_interval:     30s
  evaluation_interval: 30s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'kafka-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka_exporter:9308']
  - job_name: "node-exporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["node-exporter:9100"]
